name: Render website

on: [push, pull_request]

jobs:
  quarto-ubuntu:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        run: |
          cd docs
          Rscript --vanilla -e 'install.packages("rmarkdown")'
          quarto render README.qmd

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add slides/* || echo Nothing to be added
          git commit -a -m 'Re-build examples' || echo Nothing has changed
          git push origin || echo "No changes to commit"
